#!/bin/sh
# shellcheck disable=SC2016

CLANG=${1:-clang}
CLANGPP=${2:-clang++}
linker=${3:-ld.gold}

LD=$(which "${linker}")
export LDFLAGS="-fuse-ld=$LD"

SUDO='sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH'
CPUS="1"
ARCH=$(uname -m)

cd /tmp

# pre-create some directories
${SUDO} mkdir -p /usr/GNUstep/Local/Library/Libraries
${SUDO} mkdir -p /usr/GNUstep/Local/Library/Headers

# cleanup
${SUDO} rm -rf /tmp/libdispatch
${SUDO} rm -rf /tmp/libobjc2

# pull
git clone --recursive https://github.com/gnustep/libobjc2.git

# set vars
export CC="${CLANG}"
export CXX="${CLANGPP}"

# build and install
echo "======== Installing libobjc2..."
cd /tmp/libobjc2
mkdir build
cd build
cmake -DGNUSTEP_INSTALL_TYPE=SYSTEM ../ \
  -DCMAKE_C_COMPILER="${CC}" \
  -DCMAKE_CXX_COMPILER="${CXX}" \
  -DCMAKE_ASM_COMPILER="${CC}" \
  -DCMAKE_LINKER="${LD}" \
  -DCMAKE_MODULE_LINKER_FLAGS="${LDFLAGS}"
make -j${CPUS}
${SUDO} -E make install && ${SUDO} ldconfig

echo "Done."
