#!/bin/sh
# shellcheck disable=SC2016

CLANG=${1:-clang}
CLANGPP=${2:-clang++}
linker=${3:-ld.gold}

LD=$(which "${linker}")
export LDFLAGS="-fuse-ld=$LD"

SUDO='sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH'
CPUS="1"
ARCH=$(uname -m)

cd /tmp

# cleanup
${SUDO} rm -rf /tmp/libdispatch

# set vars
export CC="${CLANG}"
export CXX="${CLANGPP}"

# build and install
if [ $ARCH != arm7l ]; then
cd /tmp
git clone https://github.com/apple/swift-corelibs-libdispatch.git libdispatch
echo "======== Installing libdispatch..."
cd /tmp/libdispatch
rm -rf build
mkdir build
cd build
cmake ../ \
  -DCMAKE_C_COMPILER="${CC}" \
  -DCMAKE_CXX_COMPILER="${CXX}" \
  -DCMAKE_ASM_COMPILER="${CC}" \
  -DCMAKE_LINKER="${LD}" \
  -DCMAKE_MODULE_LINKER_FLAGS="${LDFLAGS}" \
  -DCMAKE_INSTALL_PREFIX="/usr/GNUstep/System" \
  -DCMAKE_INSTALL_BINDIR="/usr/GNUstep/System/Tools" \
  -DCMAKE_INSTALL_LIBDIR="/usr/GNUstep/System/Library/Libraries" \
  -DCMAKE_INSTALL_INCLUDEDIR="/usr/GNUstep/System/Library/Headers" \
  -DCMAKE_INSTALL_MANDIR="/usr/GNUstep/System/Library/Documentation/man" \
  -DCMAKE_INSTALL_INFODIR="/usr/GNUstep/System/Library/Documentation/info" \
  -DCMAKE_INSTALL_DOCDIR="/usr/GNUstep/System/Library/Documentation" \
  -DCMAKE_INSTALL_DATAROOTDIR="/usr/GNUstep/System/Library" \
  -DTESTS=OFF
make -j${CPUS}
${SUDO} -E make install && ${SUDO} ldconfig
fi

echo "Done."